### ISSUE TITLE
Were MD5 checksums removed intentionally?

### ISSUE THREAD

**Issue by sdasda7777** [ip7z/7zip#1]
Hi, I could swear 7-zip had option to create MD5 hash of a file through the CRC SHA, but now I can't seem to find a way to do it, only CRC or SHA. Am I misremembering? If not, would it be possible to bring this feature back?

**Comment by ip7z** [comment]
Maybe you used external 7-Zip plugins or some fork of 7-Zip?
https://www.tc4shell.com/en/7zip/

**Comment by inkydragon** [comment]
Maybe you are looking for https://github.com/mcmilk/7-Zip-zstd

> these hashes can be calculated: CRC32, CRC64, MD2, MD4, _MD5_, SHA1, SHA256, SHA384, SHA512, SHA3-256, SHA3-384, SHA3-512, XXH32, XXH64, BLAKE2sp, BLAKE3 (lowercase or uppercase)

**Comment by SwimmeRM** [comment]
Even after doing a quick check into latest beta history.txt file it turns out that MD5 checksum support was indeed never added. And here's also the excerpt clarifying when and which hashing types were added into 7-Zip.
"...
9.25 alpha     2011-09-16
-------------------------
...
- New command "h" to calculate hash values CRC-32, CRC-64, SHA-256 or SHA-1 for files on disk.
..."

Nevertheless, I can also very easily assume that any user might indeed have already seen "md5" mentioned by 7-zip itself. Just see below small excerpts from following command lines only 7-Zip commands :
- **7z.exe -i**
"...
   CK.....O.....XC........  Hash     sha256 sha512 sha224 sha384 sha1 sha md5 cr
c32 crc64 asc cksum
..."
- **7za.exe -i**
"...
   CK.....O.....XC........  Hash     sha256 sha512 sha224 sha384 sha1 sha md5 cr
c32 crc64 asc cksum
..."

**Comment by Perkolator** [comment]
> And main reason for this is also understandable...

The OP was talking about "creating a MD5 hash of a file", for which the MD5 is fine. For cryptography the MD5 should not be used anymore.

**Comment by AlttiRi** [comment]
It finally calculates MD5 when you select `*` option. 
_It was annoying AF to use online sites (for example, [md5file](https://md5file.com/calculator)) to calculate MD5._ 
> 24.09          2024-11-29
> - 7-Zip now can calculate the following hash checksums: SHA-512, SHA-384, SHA3-256 and MD5.

BTW, also in the latest release:
> - The default dictionary size values for LZMA/LZMA2 compression methods were increased

Wow, two notable quality of life improvement in one release.

**Comment by sdasda7777** [comment]
That's really nice, thank you!
